name: Endor Labs Scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  endorlabs-scan:
    permissions:
      id-token: write # This is required for requesting the JWT
      # contents: read # Only needed if the repo is private
      # security-events: write # Only needed to upload findings to GitHub
      # actions: read # Only needed to upload findings to GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
      - name: Create lockfile
        run: dotnet restore --use-lock-file ./src
      - name: Endor Labs Watch
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: endorlabs/github-action@main
        with:
          namespace: "example" # Update with your Endor Labs namespace
          scan_summary_output_type: "table"
          ci_run: "false"
          enable_github_action_token: "true"
          sarif_file: endorlabs.sarif
          additional_args: "--enable=git,analytics,secrets"
      - name: Endor Labs Scan PR to Default Branch
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@main
        with:
          namespace: "example" # Update with your Endor Labs namespace
          scan_summary_output_type: "table"
          ci_run: "true"
          enable_github_action_token: "true"
          sarif_file: endorlabs.sarif
          additional_args: "--enable=git,analytics,secrets --ci-baseline=dev"
     # Use for to upload findings to GitHub.
     # - name: Upload SARIF to github
     #   if: github.event_name == 'push'
     #   uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
     #   with:
     #     sarif_file: endorlabs.sarif
