name: Python Application CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py install

    - name: Endor Labs Watch
      if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      uses: endorlabs/github-action@main
      with:
        namespace: "example" # Update with your Endor Labs namespace
        scan_summary_output_type: "table"
        ci_run: "false"
        enable_github_action_token: "true"
        sarif_file: endorlabs.sarif
        additional_args: "--enable=git,analytics,secrets"
    - name: Endor Labs Scan PR to Default Branch
      if: github.event_name == 'pull_request'
      uses: endorlabs/github-action@main
      with:
        namespace: "example" # Update with your Endor Labs namespace
        scan_summary_output_type: "table"
        ci_run: "true"
        enable_github_action_token: "true"
        sarif_file: endorlabs.sarif
        additional_args: "--enable=git,analytics,secrets --ci-baseline=dev"
     # Use for to upload findings to GitHub.
     # - name: Upload SARIF to github
     #   if: github.event_name == 'push'
     #   uses: github/codeql-action/upload-sarif@9885f86fab4879632b7e44514f19148225dfbdcd
     #   with:
     #     sarif_file: endorlabs.sarif
