version: 2.1

jobs:
  test-endorlabs-scan:
    docker:
      - image: maven:3.6.3-jdk-11 # Modify this image as needed for your build tools
    environment:
      ENDORCTL_VERSION: "latest"
      ENDOR_NAMESPACE: "yolo"
      DEBUG: "false"
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            mvn clean install -Dskiptests
      - run:
          name: "Install endorctl"
          command: |
            apt-get update && apt-get install -y jq
            if [ "$ENDORCTL_VERSION" == "latest" ]; then
              echo "Downloading latest version of endorctl"
              VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
              ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
              curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
              echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
              if [ $? -ne 0 ]; then
                echo "Integrity check failed"
                exit 1
              fi
            else
              echo "Downloading version $ENDORCTL_VERSION of endorctl"
              curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
              # You need to set ENDORCTL_SHA here if you are using it in the integrity check
            fi
            chmod +x ./endorctl
            ./endorctl --version
      - run:
          name: "Endor Labs Test"
          command: |
            ./endorctl scan --pr --pr-baseline=main --dependencies --secrets
  watch-endorlabs-scan:
    docker:
      - image: maven:3.6.3-jdk-11 # Modify this image as needed for your build tools
    environment:
      ENDORCTL_VERSION: "latest"
      ENDOR_NAMESPACE: "yolo"
      DEBUG: "false"
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            mvn clean install -Dskiptests
      - run:
          name: "Install endorctl"
          command: |
            apt-get update && apt-get install -y jq
            if [ "$ENDORCTL_VERSION" == "latest" ]; then
              echo "Downloading latest version of endorctl"
              VERSION=$(curl https://api.endorlabs.com/meta/version | jq -r '.Service.Version')
              ENDORCTL_SHA=$(curl https://api.endorlabs.com/meta/version | jq -r '.ClientChecksums.ARCH_TYPE_LINUX_AMD64')
              curl https://storage.googleapis.com/endorlabs/"$VERSION"/binaries/endorctl_"$VERSION"_linux_amd64 -o endorctl
              echo "$ENDORCTL_SHA  endorctl" | sha256sum -c
              if [ $? -ne 0 ]; then
                echo "Integrity check failed"
                exit 1
              fi
            else
              echo "Downloading version $ENDORCTL_VERSION of endorctl"
              curl https://storage.googleapis.com/endorlabs/"$ENDORCTL_VERSION"/binaries/endorctl_"$ENDORCTL_VERSION"_linux_amd64 -o endorctl
              # You need to set ENDORCTL_SHA here if you are using it in the integrity check
            fi
            chmod +x ./endorctl
            ./endorctl --version
      - run:
          name: "Endor Labs Watch"
          command: |
            ./endorctl scan --dependencies --secrets
workflows:
  build_and_endorlabs_watch:
    when:
      equal: [ main, << pipeline.git.branch >> ]
    jobs:
      - watch-endorlabs-scan:
          context:
            - endorlabs
  build_and_endorlabs_test:
    jobs:
      - test-endorlabs-scan:
          context:
            - endorlabs
